
name: Download Nifty 50 Data and Save to CSV

on:
  schedule:
    # This will run at 4:30 PM IST every day (converted to UTC time 11:30 AM)
    - cron: '30 11 * * *'  # UTC time equivalent to 4:30 PM IST (UTC +5:30)
  workflow_dispatch:  # Allow manual trigger

jobs:
  download_and_save_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      # Step 4: Run the Python script to download and save data
      - name: Run download and save data script
        run: |
          python download_nifty50.py

      # Step 5: Commit and push the updated CSV file to GitHub
      - name: Commit and push CSV to GitHub
        run: |
          git config --global user.name 'your-github-username'
          git config --global user.email 'your-email@example.com'
          git add data/nifty50_data.csv
          git commit -m "Update Nifty 50 data CSV"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
