name: Predict RNN

on:
  workflow_dispatch: # Allows manual trigger
  schedule: # Optional: Schedule for running the workflow
    - cron: "0 * * * *" # Runs every hour (adjust as needed)

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow pandas numpy scikit-learn

      # Step 4: Ensure necessary directories and files exist
      - name: Ensure prediction file exists
        run: |
          mkdir -p data
          if [ ! -f data/prediction.csv ]; then
            echo "Creating an empty prediction.csv file"
            echo "Timestamp,15_min,30_min,45_min,60_min" > data/prediction.csv
          fi

      # Step 5: Run prediction script
      - name: Run prediction script
        run: python predict_rnn.py

      # Step 6: Commit and push updated predictions
      - name: Commit Predictions
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your_email@example.com"
          git add data/prediction.csv
          git commit -m "Updated predictions" || echo "No changes to commit"
          git push
