name: Predict with RNN

on:
  schedule:
    - cron: '0/15 4-10 * * 1-5' # Every 15 minutes from 9:30 AM to 3:15 PM IST (Monday to Friday)
  workflow_dispatch: # Allows manual trigger

jobs:
  predict_rnn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pandas numpy tensorflow

      - name: Run prediction script
        run: python predict_rnn.py

      - name: Commit and push predictions
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add data/prediction.csv
          git commit -m "Update prediction data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
