name: Predict RNN

on:
  workflow_dispatch: # Allows manual trigger
  schedule: # Optional: Run at specified times
    - cron: "0 * * * *" # Every hour (adjust as needed)

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow pandas numpy scikit-learn

      # Step 4: Check if prediction.csv exists and add it
      - name: Check if prediction.csv exists and add it
        run: |
          if [ ! -f data/prediction.csv ]; then
            echo "Timestamp,15_min,30_min,45_min,60_min" > data/prediction.csv
          fi
          git status  # Check if the file is detected by git
          git add data/prediction.csv  # Ensure the file is added

      # Step 5: Run prediction script
      - name: Run prediction script
        run: python predict_rnn.py

      # Step 6: Add and commit the file with updated predictions
      - name: Commit and push changes
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your_email@example.com"
          git status  # Confirm file is staged
          git commit -m "Updated predictions" || echo "No changes to commit"
          git push
