name: Predict Nifty 50 Index

on:
  schedule:
    # Run every 15 minutes between 9:30 AM and 3:15 PM IST
    - cron: '45 4-9 * * 1-5'  # 9:30 AM IST to 3:15 PM IST (Monday-Friday)
    - cron: '45 4 * * 6'      # 9:30 AM IST (Saturday)

jobs:
  predict-nifty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install pandas numpy tensorflow sklearn

      - name: Run Prediction Script
        run: |
          python predict_rnn.py

      - name: Commit and Push Predictions
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add data/prediction.csv
          git commit -m "Update predictions from RNN"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
