name: Train RNN Model

on:
  schedule:
    # Run every Saturday at 9:00 AM IST
    - cron: '30 3 * * 6'  # 9:00 AM IST = 3:30 AM UTC
  workflow_dispatch:

jobs:
  train-rnn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install pandas numpy tensorflow scikit-learn

      - name: Train RNN Model
        run: |
          python train_rnn.py

      - name: Commit and Push Model
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add RNN_model/
          git commit -m "Update RNN model on Saturday training"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
